server:
  port: 8888
  context-path: /backApp
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://10.104.207.96:5432/ifamily?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
        username: postgres
        password: postgres
        druid:
              #初始化连接大小
              initial-size: 8
              #最小空闲连接数
              min-idle: 5
              #最大连接数
              max-active: 10
              #查询超时时间
              query-timeout: 6000
              #事务查询超时时间
              transaction-query-timeout: 6000
              #关闭空闲连接超时时间
              remove-abandoned-timeout: 1800
              filters: stat,config

mybatis:
  mapUnderscoreToCamelCase: true
  typeAliasesPackage: com.hxlc.backstageapp.pojo
  mapperLocations: classpath:static/mappers/*.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.hxlc.backstageapp.mapper: debug
